### ISSUE TITLE
Memory Editing

### ISSUE THREAD

**Issue by fallenlucario** [FullLifeGames/Mass-Editor#1]
Hi, I'd just like to thank you for making this amazing application as it has saved me a lot of time editing multiple pokemon to fit a certain template!

With that being said, the only issue I've found with this application is when I edit the memories

I'm trying to set it so all my pokemon have a memory in "a simple town" but every time I edit them , they come out with "a battling spot"

I've just tested out a different memory and area. Seems the (2) Area texts are bugged to only display "a battling spot" Aside from that everything else is in working order, I'd just suggest you test a bit.

Also one random question.
For the date editing (Met date and egg met conditions) Would it be possible to edit the Month,Day, and Year Values separately? For example, my pokemon are met all on random dates, but I'd only like to edit the Year so they're all in 2015 (a year after all the XY/ORAS games were released) But I'd like to keep the random dates for them to not all be from the same date.

Just thought it'd be a useful little addition.

**Comment by FullLifeGames** [comment]
Fixed with: https://github.com/FullLifeGames/Mass-Editor/commit/67dd02c27bd56c477f181e6cc5c919282f5eb0a8
