### ISSUE TITLE
supporting other gens

### ISSUE THREAD

**Issue by NinFanBoyFTW** [FullLifeGames/Mass-Editor#10]
Hi I wanted to know if you are adding support for every other gen of pokemon like pkhex has begun to support. I would love to use this program not just for 6th gen and soon 7th gen but also 1-5th gen

**Comment by FullLifeGames** [comment]
I don't know how they're supporting the old gens. I might look into that, but for now this Mass-Editor will only support Gen 6 and Gen 7.

**Comment by FullLifeGames** [comment]
I have a Mass Editor for Gen 6 and one for Gen 7, other Gens won't be supported.
