### ISSUE TITLE
My Pokemon become all Arceus

### ISSUE THREAD

**Issue by zFeraz** [FullLifeGames/Mass-Editor#11]
When I try to edit my pokemons I get only Arceus with stange statistics.
[GeneratedBoxFile0.zip](https://github.com/FullLifeGames/Mass-Editor/files/628933/GeneratedBoxFile0.zip)

**Comment by FullLifeGames** [comment]
I can't open your zip file, so I can't really help you with this.

**Comment by FullLifeGames** [comment]
Ah, I see your problem. Don't use the new version of Mass Editor with an old PKHeX version, because these don't support pk7 files!

**Comment by zFeraz** [comment]
I used latest version on github

**Comment by zFeraz** [comment]
Can you give me a link to the last version so I can compare?

**Comment by FullLifeGames** [comment]
Did you compile the code yourself, or did you use this release: https://github.com/FullLifeGames/Mass-Editor/blob/master/bin/Release/Mass%20Editor.exe

**Comment by zFeraz** [comment]
I compiled it but now i'm triyng release

**Comment by zFeraz** [comment]
Doesn't work...Can you send me to this email  (fedeaki12@gmail.com) a zip with Pkhex and Mass editor?

**Comment by FullLifeGames** [comment]
Give me your input and output.

**Comment by zFeraz** [comment]
I don't understand

**Comment by zFeraz** [comment]
Listen, I just need a zip with pkhex and mass editor

**Comment by FullLifeGames** [comment]
http://puu.sh/sFm9x/b5955fd839.zip

**Comment by zFeraz** [comment]
Thanks now works I'll wait for pk7 support release
