### ISSUE TITLE
Update on Release requested?

### ISSUE THREAD

**Issue by BaiqingL** [FullLifeGames/Mass-Editor#12]
Hello FullLifeGames,

Is it possible to update the Github release link for a compiled version of Mass-Editor? Currently I just switched to fully Linux and it is a pain to compile with errors occurring every 30 seconds.

Would it be possible for you to compile a version and release it on the Releases tab? Or update the "https://raw.githubusercontent.com/FullLifeGames/Mass-Editor/master/bin/Release/Mass%20Editor.exe" links.

Thanks, I do know that you might not want to do it for certain reasons, you can close this issue without responding if so.

**Comment by FullLifeGames** [comment]
The current version doesn't work for Sun & Moon and really doesn't work that well at all and needs work.

**Comment by FullLifeGames** [comment]
https://github.com/FullLifeGames/Mass-Editor/tree/67dd02c27bd56c477f181e6cc5c919282f5eb0a8
Try to get it from here.

**Comment by FullLifeGames** [comment]
Or try now again, I updated the version to support gen 7!

**Comment by BaiqingL** [comment]
Thanks! I lost access to my account for a few days since I forgot the device that had 2FA... Thanks for the replies :) @FullLifeGames
