### ISSUE TITLE
The latest build is broken

### ISSUE THREAD

**Issue by Araraura** [FullLifeGames/Mass-Editor#13]
Everytime i press mass edit after editing something, the program crash, it also crashes when i try to choose any ribbon and also, almost the entire "Change Met to" have empty tabs.

**Comment by FullLifeGames** [comment]
This one? https://github.com/FullLifeGames/Mass-Editor/blob/master/bin/Release/Mass%20Editor.exe

**Comment by FullLifeGames** [comment]
Try again, should work now with Gen 7 files. 3ca31d26811c892f741056deba8aa588ce5f1d39
