### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fallenlucario** [FullLifeGames/Mass-Editor#2]
I just realized that i forgot to mention this! I think you should implement a button to reset EVs to 0 where the rest of the options are at the top such as the make pokemon shiny, reroll pid/encryption, and make everything perfect IV buttons.

**Comment by FullLifeGames** [comment]
Added with: https://github.com/FullLifeGames/Mass-Editor/commit/9e89feb52534c50dca5f2048a185d55e29bc5c29
