### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fallenlucario** [FullLifeGames/Mass-Editor#4]
Will there be a new release of this with the previous changed you made from my other posts or do I have to compile it. If I have to compile it, could you tell me how I would go about doing so as i want to use the program with the new enhancement and bug fix. Thank you! (:

**Comment by FullLifeGames** [comment]
Isn't this the new version: https://github.com/FullLifeGames/Mass-Editor/blob/master/bin/Release/Mass%20Editor.exe?raw=true ? Can you test it and tell me, if the features are included?

**Comment by fallenlucario** [comment]
Ah i see, I'm sorry usually people have their releases listed under a link like this: https://github.com/FullLifeGames/Mass-Editor/releases

so when i saw nothing there in the releases, I didn't know where the exe file was.

I can see the set evs to 0 button, I will try out some memory editing later today or tomorrow and report back to you!
