### ISSUE TITLE
Friendship bug

### ISSUE THREAD

**Issue by fallenlucario** [FullLifeGames/Mass-Editor#6]
Hey I'm having an issue with the friendship editing, when i put 255 it stays at 0 for pokemon i try to edit.
Also where do you post the releases for this once you've made corrections, before I had a hard time finding it until you linked me

**Comment by Pkmnninja** [comment]
I have been experiencing this bug and would be a big help to get it fixed ASAP as i need to edit the friendship of my entire living dex which will take ages manually

**Comment by FullLifeGames** [comment]
I will look into it!

**Comment by FullLifeGames** [comment]
Tested the Friendship functionality and the Change MemoryAmie function with the new version and both seem to work. Can't be reproduced!
