### ISSUE TITLE
Files Don't Save

### ISSUE THREAD

**Issue by joshuarosato** [FullLifeGames/Mass-Editor#7]
After editing files and importing them into PKHeX, no changes appear to have been made.

I have tried running the program as admin, but then I am not able to load files.

**Comment by SXRWahrheit** [comment]
Same issue

**Comment by FullLifeGames** [comment]
Strange, could you give me an example input?

**Comment by FullLifeGames** [comment]
No example input and new version released. Can't be reproduced!
