### ISSUE TITLE
Doesn't work for .pk7 files

### ISSUE THREAD

**Issue by mjd85** [FullLifeGames/Mass-Editor#9]

**Comment by FullLifeGames** [comment]
The whole project has to be reworked to:
a) Support the new structure of PKHeX
b) Support the new Sun & Moon changes

This will be a lot of work, since I made my implementation too reliant on the old implementation. This is on my TODO list however.

**Comment by FullLifeGames** [comment]
Support for .pk7 files added with 3ca31d26811c892f741056deba8aa588ce5f1d39
